# Generated by Django 4.1 on 2024-05-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
