# Generated by Django 4.1 on 2024-05-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_video', '0002_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
